# Tracing with the AWS Distro for OpenTelemetry Python Auto-Instrumentation and X-Ray | AWS Open Distro for OpenTelemetry
# https://aws-otel.github.io/docs/getting-started/python-sdk/trace-auto-instr
- name: Install required packages for instrumentation and to support tracing with AWS X-Ray
  become: true
  become_user: isucon
  ansible.builtin.pip:
    name:
      - "opentelemetry-distro[otlp]>=0.24b0"
      - "opentelemetry-sdk-extension-aws~=2.0"
      - "opentelemetry-propagator-aws-xray~=1.0"
    virtualenv: /home/isucon/private_isu/webapp/python/venv

- name: Automatically install supported Instrumentors for the application's dependencies
  become: true
  become_user: isucon
  ansible.builtin.shell: venv/bin/opentelemetry-bootstrap --action=install && touch /home/isucon/.config/opentelemetry-bootstrap-installed
  args:
    chdir: /home/isucon/private_isu/webapp/python
    creates: /home/isucon/.config/opentelemetry-bootstrap-installed

- name: copy additional otel instrument
  become: true
  become_user: isucon
  ansible.builtin.copy:
    src: home/isucon/private_isu/webapp/python/opentelemetry_instrumentation_mysqlclient.py
    dest: /home/isucon/private_isu/webapp/python/opentelemetry_instrumentation_mysqlclient.py
    owner: isucon
    group: isucon
    mode: "0664"
    backup: yes

- name: copy gunicorn config
  become: true
  become_user: isucon
  ansible.builtin.copy:
    src: home/isucon/private_isu/webapp/python/gunicorn.conf.py
    dest: /home/isucon/private_isu/webapp/python/gunicorn.conf.py
    owner: isucon
    group: isucon
    mode: "0664"
    backup: yes

- name: copy systemd unit file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: etc/systemd/system/isu-python-adot.service
    dest: /etc/systemd/system/isu-python-adot.service
    owner: root
    group: root
    mode: "0644"

- name: systemd stop, disable isu-python
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: isu-python
    state: stopped
    enabled: no

- name: systemd start, enable isu-python-adot
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: isu-python-adot
    state: started
    enabled: yes
    daemon_reload: yes
